[project]
name = "csbsr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.9.0",
    "ninja>=1.11.0",
    "numpy>=1.26.0,<2.0",
    "opencv-python>=4.9.0",
    "pandas>=2.1.0",
    "pillow>=10.2.0",
    "protobuf==3.20.1",
    "scikit-image>=0.22.0",
    "tensorboard>=2.16.0",
    "timm>=0.9.0",
    "torch>=2.1.0,<2.5",
    "torchvision>=0.16.0,<0.20",
    "tqdm>=4.66.0",
    "wandb>=0.16.0",
    "yacs>=0.1.8",
]
